### ISSUE TITLE
Add Algolia DocSearch input

### ISSUE THREAD

**Issue by hbs** [cityzendata/www.warp10.io#4]

**Comment by hbs** [comment]
Search box should be more centered as the results are truncated on the right if the box is too much on the right side of the page

**Comment by LostInBrittany** [comment]
IMO it's the Algolia popup that should be more centered, I'm going to try to do it with Algolia CSS classes...

**Comment by LostInBrittany** [comment]
Corrected in commit 48b0414039d6bbff6dd719744ba53c144c2589f1
